export const DOCUMENT_OPTIONS = [
    { value: "CE", label: "Foreigner ID (CE)" },
    { value: "PASAPORTE", label: "Passport" },
    { value: "CC", label: "National ID (CC)" },
    { value: "TI", label: "Identity Card (TI)" },
    { value: "NIT", label: "Tax ID (NIT)" },
]

export const GENDER_OPTIONS = [
    { value: "male", label: "Male" },
    { value: "female", label: "Female" },
]

export const GUEST_OPTIONS = [
    { value: "1", label: "1 guest" },
    { value: "2", label: "2 guests" },
    { value: "3", label: "3 guests" },
    { value: "4", label: "4 guests" },
]

export const NATIONALITY_OPTIONS = [
    { value: "Colombiano", label: "Colombiano" },
    { value: "Ecuadoriano", label: "Ecuadoriano" },
    { value: "Afgano", label: "Afgano" },
    { value: "Albanés", label: "Albanés" },
    { value: "Alemán", label: "Alemán" },
    { value: "Andorrano", label: "Andorrano" },
    { value: "Angoleño", label: "Angoleño" },
    { value: "Anguileño", label: "Anguileño" },
    { value: "Antiguano", label: "Antiguano" },
    { value: "Argentino", label: "Argentino" },
    { value: "Armenio", label: "Armenio" },
    { value: "Australiano", label: "Australiano" },
    { value: "Austriaco", label: "Austriaco" },
    { value: "Azerbaiyano", label: "Azerbaiyano" },
    { value: "Bahameño", label: "Bahameño" },
    { value: "Bahreiní", label: "Bahreiní" },
    { value: "Bangladesí", label: "Bangladesí" },
    { value: "Barbadense", label: "Barbadense" },
    { value: "Beliceño", label: "Beliceño" },
    { value: "Beninés", label: "Beninés" },
    { value: "Bermudeño", label: "Bermudeño" },
    { value: "Bielorruso", label: "Bielorruso" },
    { value: "Boliviano", label: "Boliviano" },
    { value: "Bosnio", label: "Bosnio" },
    { value: "Botswanés", label: "Botswanés" },
    { value: "Brasileño", label: "Brasileño" },
    { value: "Bruneano", label: "Bruneano" },
    { value: "Búlgaro", label: "Búlgaro" },
    { value: "Burkinés", label: "Burkinés" },
    { value: "Burundés", label: "Burundés" },
    { value: "Butanés", label: "Butanés" },
    { value: "Belga", label: "Belga" },
    { value: "Cabo Verdeano", label: "Cabo Verdeano" },
    { value: "Camboyano", label: "Camboyano" },
    { value: "Canadiense", label: "Canadiense" },
    { value: "Chadiano", label: "Chadiano" },
    { value: "Chileno", label: "Chileno" },
    { value: "Chino", label: "Chino" },
    { value: "Chipriota", label: "Chipriota" },
    { value: "Coreano", label: "Coreano" },
    { value: "Costarricense", label: "Costarricense" },
    { value: "Croata", label: "Croata" },
    { value: "Cubano", label: "Cubano" },
    { value: "Danés", label: "Danés" },
    { value: "Dominiqués", label: "Dominiqués" },
    { value: "Egipcio", label: "Egipcio" },
    { value: "Salvadoreño", label: "Salvadoreño" },
    { value: "Emiratí", label: "Emiratí" },
    { value: "Eritreo", label: "Eritreo" },
    { value: "Eslovaco", label: "Eslovaco" },
    { value: "Esloveno", label: "Esloveno" },
    { value: "Español", label: "Español" },
    { value: "Estadounidense", label: "Estadounidense" },
    { value: "Estonio", label: "Estonio" },
    { value: "Etiope", label: "Etiope" },
    { value: "Filipino", label: "Filipino" },
    { value: "Finlands", label: "Finlandés" },
    { value: "Francés", label: "Francés" },
    { value: "Gabonés", label: "Gabonés" },
    { value: "Gambiano", label: "Gambiano" },
    { value: "Georgiano", label: "Georgiano" },
    { value: "Ghanés", label: "Ghanés" },
    { value: "Gibraltareño", label: "Gibraltareño" },
    { value: "Británico", label: "Británico" },
    { value: "Granadino", label: "Granadino" },
    { value: "Griego", label: "Griego" },
    { value: "Groenlandés", label: "Groenlandés" },
    { value: "Guadalupeño", label: "Guadalupeño" },
    { value: "Guameño", label: "Guameño" },
    { value: "Guatemalteco", label: "Guatemalteco" },
    { value: "Guayanés", label: "Guayanés" },
    { value: "Guineano", label: "Guineano" },
    { value: "Haitiano", label: "Haitiano" },
    { value: "Hondureño", label: "Hondureño" },
    { value: "Hongkonés", label: "Hongkonés" },
    { value: "Húngaro", label: "Húngaro" },
    { value: "Indio", label: "Indio" },
    { value: "Indonesio", label: "Indonesio" },
    { value: "Iraquí", label: "Iraquí" },
    { value: "Iraní", label: "Iraní" },
    { value: "Islandés", label: "Islandés" },
    { value: "Israelí", label: "Israelí" },
    { value: "Italiano", label: "Italiano" },
    { value: "Jamaicano", label: "Jamaicano" },
    { value: "Japonés", label: "Japonés" },
    { value: "Jordano", label: "Jordano" },
    { value: "Kazajo", label: "Kazajo" },
    { value: "Keniano", label: "Keniano" },
    { value: "Kirguís", label: "Kirguís" },
    { value: "Kuwaití", label: "Kuwaití" },
    { value: "Laosiano", label: "Laosiano" },
    { value: "Lesotense", label: "Lesotense" },
    { value: "Letón", label: "Letón" },
    { value: "Liberiano", label: "Liberiano" },
    { value: "Libio", label: "Libio" },
    { value: "Liechtensteiniano", label: "Liechtensteiniano" },
    { value: "Lituano", label: "Lituano" },
    { value: "Luxemburgués", label: "Luxemburgués" },
    { value: "Libanés", label: "Libanés" },
    { value: "Macanés", label: "Macanés" },
    { value: "Macedonio", label: "Macedonio" },
    { value: "Madagascarí", label: "Madagascarí" },
    { value: "Malasio", label: "Malasio" },
    { value: "Malawiano", label: "Malawiano" },
    { value: "Malí", label: "Malí" },
    { value: "Maltés", label: "Maltés" },
    { value: "Marfileño", label: "Marfileño" },
    { value: "Mauritano", label: "Mauritano" },
    { value: "Mexicano", label: "Mexicano" },
    { value: "Moldavo", label: "Moldavo" },
    { value: "Mongol", label: "Mongol" },
    { value: "Montenegrino", label: "Montenegrino" },
    { value: "Mozambiqueño", label: "Mozambiqueño" },
    { value: "Birmano", label: "Birmano" },
    { value: "Monegasco", label: "Monegasco" },
    { value: "Namibio", label: "Namibio" },
    { value: "Nauruano", label: "Nauruano" },
    { value: "Nepalí", label: "Nepalí" },
    { value: "Nicaragüense", label: "Nicaragüense" },
    { value: "Nigeriano", label: "Nigeriano" },
    { value: "Noruego", label: "Noruego" },
    { value: "Neozelandés", label: "Neozelandés" },
    { value: "Omaní", label: "Omaní" },
    { value: "Pakistaní", label: "Pakistaní" },
    { value: "Palestino", label: "Palestino" },
    { value: "Panameño", label: "Panameño" },
    { value: "Papú", label: "Papú" },
    { value: "Paraguayo", label: "Paraguayo" },
    { value: "Holandés", label: "Holandés" },
    { value: "Peruano", label: "Peruano" },
    { value: "Polinesio", label: "Polinesio" },
    { value: "Polaco", label: "Polaco" },
    { value: "Portugués", label: "Portugués" },
    { value: "Puertorriqueño", label: "Puertorriqueño" },
    { value: "Qatarí", label: "Qatarí" },
    { value: "Camerunés", label: "Camerunés" },
    { value: "Centroafricano", label: "Centroafricano" },
    { value: "Checo", label: "Checo" },
    { value: "Congoleño", label: "Congoleño" },
    { value: "Dominicano", label: "Dominicano" },
    { value: "Irlandés", label: "Irlandés" },
    { value: "Ruandés", label: "Ruandés" },
    { value: "Rumano", label: "Rumano" },
    { value: "Ruso", label: "Ruso" },
    { value: "Saharaui", label: "Saharaui" },
    { value: "Samoano", label: "Samoano" },
    { value: "Sanmarinense", label: "Sanmarinense" },
    { value: "Sanvicentino", label: "Sanvicentino" },
    { value: "Santa Lucense", label: "Santa Lucense" },
    { value: "Senegalés", label: "Senegalés" },
    { value: "Serbio", label: "Serbio" },
    { value: "Sierraleonés", label: "Sierraleonés" },
    { value: "Singapurense", label: "Singapurense" },
    { value: "Sirioc", label: "Sirio" },
    { value: "Somalí", label: "Somalí" },
    { value: "Ceylonés", label: "Ceylonés" },
    { value: "Sudafricano", label: "Sudafricano" },
    { value: "Sudanés", label: "Sudanés" },
    { value: "Sueco", label: "Sueco" },
    { value: "Suizo", label: "Suizo" },
    { value: "Surinamés", label: "Surinamés" },
    { value: "Tailandés", label: "Tailandés" },
    { value: "Taiwanés", label: "Taiwanés" },
    { value: "Tanzano", label: "Tanzano" },
    { value: "Tayiko", label: "Tayiko" },
    { value: "Timorense", label: "Timorense" },
    { value: "Togolés", label: "Togolés" },
    { value: "Tonganés", label: "Tonganés" },
    { value: "Trinidadense", label: "Trinidadense" },
    { value: "Turcomano", label: "Turcomano" },
    { value: "Turco", label: "Turco" },
    { value: "Tuvaluano", label: "Tuvaluano" },
    { value: "Tunecino", label: "Tunecino" },
    { value: "Ucraniano", label: "Ucraniano" },
    { value: "Ugandés", label: "Ugandés" },
    { value: "Uruguayo", label: "Uruguayo" },
    { value: "Uzbeko", label: "Uzbeko" },
    { value: "Vanuatuense", label: "Vanuatuense" },
    { value: "Vaticano", label: "Vaticano" },
    { value: "Venezolano", label: "Venezolano" },
    { value: "Vietnamita", label: "Vietnamita" },
    { value: "Yemení", label: "Yemení" },
    { value: "Yibutiano", label: "Yibutiano" },
    { value: "Zambiano", label: "Zambiano" },
    { value: "Zimbabuense", label: "Zimbabuense" },
]

export const COUNTRY_OPTIONS = [
    { value: "Colombia", label: "Colombia" },
    { value: "Ecuador", label: "Ecuador" },
    { value: "Afganistán", label: "Afganistán" },
    { value: "Albania", label: "Albania" },
    { value: "Alemania", label: "Alemania" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Anguilla", label: "Anguilla" },
    { value: "Antigua y Barbuda", label: "Antigua y Barbuda" },
    { value: "Antártida", label: "Antártida" },
    { value: "Arabia Saudí", label: "Arabia Saudí" },
    { value: "Argentina", label: "Argentina" },
    { value: "Armenia", label: "Armenia" },
    { value: "Aruba", label: "Aruba" },
    { value: "Australia", label: "Australia" },
    { value: "Austria", label: "Austria" },
    { value: "Azerbaiyán", label: "Azerbaiyán" },
    { value: "Bahamas", label: "Bahamas" },
    { value: "Bahrein", label: "Bahrein" },
    { value: "Bangladesh", label: "Bangladesh" },
    { value: "Barbados", label: "Barbados" },
    { value: "Belice", label: "Belice" },
    { value: "Benín", label: "Benín" },
    { value: "Bermudas", label: "Bermudas" },
    { value: "Bielorusia", label: "Bielorusia" },
    { value: "Bolivia", label: "Bolivia" },
    { value: "Bonaire, San Eustaquio y Saba", label: "Bonaire, San Eustaquio y Saba" },
    { value: "Bosnia-Herzegovina", label: "Bosnia-Herzegovina" },
    { value: "Botswana", label: "Botswana" },
    { value: "Brasil", label: "Brasil" },
    { value: "Brunei Darussalam", label: "Brunei Darussalam" },
    { value: "Bulgaria", label: "Bulgaria" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Burundi", label: "Burundi" },
    { value: "Bután", label: "Bután" },
    { value: "Bélgica", label: "Bélgica" },
    { value: "Cabo Verde (República)", label: "Cabo Verde (República)" },
    { value: "Camboya", label: "Camboya" },
    { value: "Canadá", label: "Canadá" },
    { value: "Chad", label: "Chad" },
    { value: "Chile", label: "Chile" },
    { value: "China", label: "China" },
    { value: "Chipre", label: "Chipre" },
    { value: "Congo Brazzaville", label: "Congo Brazzaville" },
    { value: "Corea del Norte", label: "Corea del Norte" },
    { value: "Corea del Sur (República)", label: "Corea del Sur (República)" },
    { value: "Costa Rica", label: "Costa Rica" },
    { value: "Costa de Marfil", label: "Costa de Marfil" },
    { value: "Croacia", label: "Croacia" },
    { value: "Cuba", label: "Cuba" },
    { value: "Curaçao", label: "Curaçao" },
    { value: "Dinamarca", label: "Dinamarca" },
    { value: "Dominica", label: "Dominica" },
    { value: "Egipto", label: "Egipto" },
    { value: "El Salvador", label: "El Salvador" },
    { value: "Emiratos Arabes Unidos (UAE)", label: "Emiratos Arabes Unidos (UAE)" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Eslovaquia", label: "Eslovaquia" },
    { value: "Eslovenia", label: "Eslovenia" },
    { value: "España", label: "España" },
    { value: "Estados Unidos", label: "Estados Unidos" },
    { value: "Estonia", label: "Estonia" },
    { value: "Esuatini", label: "Esuatini" },
    { value: "Etiopía", label: "Etiopía" },
    { value: "Filipinas", label: "Filipinas" },
    { value: "Finlandia", label: "Finlandia" },
    { value: "Francia", label: "Francia" },
    { value: "Gabón", label: "Gabón" },
    { value: "Gambia", label: "Gambia" },
    { value: "Georgia", label: "Georgia" },
    { value: "Ghana", label: "Ghana" },
    { value: "Gibraltar", label: "Gibraltar" },
    { value: "Gran Bretaña", label: "Gran Bretaña" },
    { value: "Granada", label: "Granada" },
    { value: "Grecia", label: "Grecia" },
    { value: "Groenlandia", label: "Groenlandia" },
    { value: "Guadalupe", label: "Guadalupe" },
    { value: "Guam", label: "Guam" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guayana", label: "Guayana" },
    { value: "Guayana Francesa", label: "Guayana Francesa" },
    { value: "Guernsey", label: "Guernsey" },
    { value: "Guinea Bisseau", label: "Guinea Bisseau" },
    { value: "Guinea Conakry", label: "Guinea Conakry" },
    { value: "Guinea Ecuatorial", label: "Guinea Ecuatorial" },
    { value: "Haití", label: "Haití" },
    { value: "Honduras", label: "Honduras" },
    { value: "Hong Kong (SAR of China)", label: "Hong Kong (SAR of China)" },
    { value: "Hungría", label: "Hungría" },
    { value: "India", label: "India" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Irak", label: "Irak" },
    { value: "Irán", label: "Irán" },
    { value: "Isla Bouvet", label: "Isla Bouvet" },
    { value: "Isla Maldivas", label: "Isla Maldivas" },
    { value: "Isla Mauricio", label: "Isla Mauricio" },
    { value: "Isla Norfolk", label: "Isla Norfolk" },
    { value: "Isla Reunión", label: "Isla Reunión" },
    { value: "Isla St. Helena", label: "Isla St. Helena" },
    { value: "Isla de Christmas", label: "Isla de Christmas" },
    { value: "Isla de Man", label: "Isla de Man" },
    { value: "Isla de San Martín", label: "Isla de San Martín" },
    { value: "Islandia", label: "Islandia" },
    { value: "Islas Aland", label: "Islas Aland" },
    { value: "Islas Caimán", label: "Islas Caimán" },
    { value: "Islas Cocos", label: "Islas Cocos" },
    { value: "Islas Comores", label: "Islas Comores" },
    { value: "Islas Cook", label: "Islas Cook" },
    { value: "Islas Faroe", label: "Islas Faroe" },
    { value: "Islas Georgias del Sur y Sandwich del Sur", label: "Islas Georgias del Sur y Sandwich del Sur" },
    { value: "Islas Heard y McDonald", label: "Islas Heard y McDonald" },
    { value: "Islas Malvinas", label: "Islas Malvinas" },
    { value: "Islas Marianas", label: "Islas Marianas" },
    { value: "Islas Marshall", label: "Islas Marshall" },
    { value: "Islas Palau", label: "Islas Palau" },
    { value: "Islas Pitcairn", label: "Islas Pitcairn" },
    { value: "Islas Salomón", label: "Islas Salomón" },
    { value: "Islas Santo Tomé y Príncipe", label: "Islas Santo Tomé y Príncipe" },
    { value: "Islas Seychelles", label: "Islas Seychelles" },
    { value: "Islas Svalbard y Jan Mayen", label: "Islas Svalbard y Jan Mayen" },
    { value: "Islas Turks y Caicos", label: "Islas Turks y Caicos" },
    { value: "Islas Vírgenes (Británicas)", label: "Islas Vírgenes (Británicas)" },
    { value: "Islas Vírgenes (EEUU)", label: "Islas Vírgenes (EEUU)" },
    { value: "Islas Wallis y Futuna", label: "Islas Wallis y Futuna" },
    { value: "Israel", label: "Israel" },
    { value: "Italia", label: "Italia" },
    { value: "Jamaica", label: "Jamaica" },
    { value: "Japón", label: "Japón" },
    { value: "Jersey", label: "Jersey" },
    { value: "Jordania", label: "Jordania" },
    { value: "Kazajistán", label: "Kazajistán" },
    { value: "Kenia", label: "Kenia" },
    { value: "Kirguizistán", label: "Kirguizistán" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Laos", label: "Laos" },
    { value: "Lesotho", label: "Lesotho" },
    { value: "Letonia", label: "Letonia" },
    { value: "Liberia", label: "Liberia" },
    { value: "Libia", label: "Libia" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Lituania", label: "Lituania" },
    { value: "Luxemburgo", label: "Luxemburgo" },
    { value: "Líbano", label: "Líbano" },
    { value: "Macao (SAR of China)", label: "Macao (SAR of China)" },
    { value: "Macedonia", label: "Macedonia" },
    { value: "Madagascar", label: "Madagascar" },
    { value: "Malasia", label: "Malasia" },
    { value: "Malaui", label: "Malaui" },
    { value: "Mali", label: "Mali" },
    { value: "Malta", label: "Malta" },
    { value: "Martinica", label: "Martinica" },
    { value: "Mauritania", label: "Mauritania" },
    { value: "Mayotte", label: "Mayotte" },
    { value: "Micronesia", label: "Micronesia" },
    { value: "Moldavia", label: "Moldavia" },
    { value: "Mongolia", label: "Mongolia" },
    { value: "Montenegro", label: "Montenegro" },
    { value: "Montserrat", label: "Montserrat" },
    { value: "Mozambique", label: "Mozambique" },
    { value: "Myanmar", label: "Myanmar" },
    { value: "México", label: "México" },
    { value: "Mónaco", label: "Mónaco" },
    { value: "Namibia", label: "Namibia" },
    { value: "Nauru", label: "Nauru" },
    { value: "Nepal", label: "Nepal" },
    { value: "Nicaragua", label: "Nicaragua" },
    { value: "Niger", label: "Niger" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Noruega", label: "Noruega" },
    { value: "Nueva Caledonia", label: "Nueva Caledonia" },
    { value: "Nueva Zelanda", label: "Nueva Zelanda" },
    { value: "Omán", label: "Omán" },
    { value: "Pakistán", label: "Pakistán" },
    { value: "Palestinian Occ. Territories", label: "Palestinian Occ. Territories" },
    { value: "Panamá", label: "Panamá" },
    { value: "Papua Nueva Guinea", label: "Papua Nueva Guinea" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "Países Bajos", label: "Países Bajos" },
    { value: "Perú", label: "Perú" },
    { value: "Polinesia Francesa", label: "Polinesia Francesa" },
    { value: "Polonia", label: "Polonia" },
    { value: "Portugal", label: "Portugal" },
    { value: "Puerto Rico", label: "Puerto Rico" },
    { value: "Qatar", label: "Qatar" },
    { value: "República Camerún", label: "República Camerún" },
    { value: "República Centro-Africana", label: "República Centro-Africana" },
    { value: "República Checa", label: "República Checa" },
    { value: "República Democrática del Congo", label: "República Democrática del Congo" },
    { value: "República Dominicana", label: "República Dominicana" },
    { value: "República Irlanda", label: "República Irlanda" },
    { value: "Ruanda", label: "Ruanda" },
    { value: "Rumanía", label: "Rumanía" },
    { value: "Rusia", label: "Rusia" },
    { value: "Sahara Occidental", label: "Sahara Occidental" },
    { value: "Samoa Americana", label: "Samoa Americana" },
    { value: "Samoa Occidental", label: "Samoa Occidental" },
    { value: "San Bartolomé", label: "San Bartolomé" },
    { value: "San Marino", label: "San Marino" },
    { value: "San Martín", label: "San Martín" },
    { value: "San Vicente y Las Granadinas", label: "San Vicente y Las Granadinas" },
    { value: "Santa Lucía", label: "Santa Lucía" },
    { value: "Senegal", label: "Senegal" },
    { value: "Serbia", label: "Serbia" },
    { value: "Sierra Leone", label: "Sierra Leone" },
    { value: "Singapur", label: "Singapur" },
    { value: "Siria", label: "Siria" },
    { value: "Somalia", label: "Somalia" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "St. Kitts", label: "St. Kitts" },
    { value: "St. Pierre y Miquelon", label: "St. Pierre y Miquelon" },
    { value: "Sudáfrica", label: "Sudáfrica" },
    { value: "Sudán", label: "Sudán" },
    { value: "Sudán del Sur", label: "Sudán del Sur" },
    { value: "Suecia", label: "Suecia" },
    { value: "Suiza", label: "Suiza" },
    { value: "Surinam", label: "Surinam" },
    { value: "Tailandia", label: "Tailandia" },
    { value: "Taiwán", label: "Taiwán" },
    { value: "Tanzania", label: "Tanzania" },
    { value: "Tayikistán", label: "Tayikistán" },
    { value: "Territorio Británico del Océano Índico", label: "Territorio Británico del Océano Índico" },
    { value: "Tierras Australes y Antárticas Francesas", label: "Tierras Australes y Antárticas Francesas" },
    { value: "Timor Leste", label: "Timor Leste" },
    { value: "Togo", label: "Togo" },
    { value: "Tokelau", label: "Tokelau" },
    { value: "Tonga", label: "Tonga" },
    { value: "Trinidad y Tobago", label: "Trinidad y Tobago" },
    { value: "Turkmenistán", label: "Turkmenistán" },
    { value: "Turquía", label: "Turquía" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "Túnez", label: "Túnez" },
    { value: "U.S. Minor Outlying Islands", label: "U.S. Minor Outlying Islands" },
    { value: "Ucrania", label: "Ucrania" },
    { value: "Uganda", label: "Uganda" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Uzbekistán", label: "Uzbekistán" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Vaticano", label: "Vaticano" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Yemén", label: "Yemén" },
    { value: "Yibuti", label: "Yibuti" },
    { value: "Zambia", label: "Zambia" },
    { value: "Zimbabue", label: "Zimbabue" },
]